// AUTO-GENERATED by scripts/parse-resume.mjs
// Re-runs automatically on `npm run dev` and `npm run build`.
// Do not edit this file manually.
import type { Experience } from "./experiences";
import type { Education } from "./education";

const resumeExperiences: Experience[] = [
  {
    "id": 1,
    "role": "Embedded Systems / Firmware Engineer",
    "company": "UBC Solar Racing (Student Design Team)",
    "companyUrl": "https://ubcsolar.com",
    "location": "Vancouver, BC",
    "period": "Sep 2024 – Present",
    "achievements": [
      "Led firmware development for the Driver Dashboard subsystem, implementing the vehicle drive-state control logic as a safety-critical state machine while integrating CAN bus messaging and hardware abstraction layers for dashboard inputs and indicators.",
      "Built a Raspberry Pi–based Python gateway connected to a Netgear hotspot to parse vehicle telemetry data and stream it to InfluxDB/Grafana, reducing latency (less than 2 seconds) and enabling the team to remotely monitor signals and diagnose errors in real time.",
      "Implemented GPS data acquisition firmware as a FreeRTOS thread that parsed NMEA sentences (GGA, GLL, GSA, RMC, VTG, GSV), validated checksums, and packaged results into CAN frames sent over a radio/cellular module, enabling the pit crew to locate the vehicle within 0.5-meter accuracy at a 200ms latency.",
      "Developed a custom steering wheel PCB with CAN bus integration, utilizing interrupt-driven firmware for turn signal capture, eco/power mode selection, and horn activation to improve driver accessibility.",
      "Designed Segger J-Link interfaces for new-generation PCBs, enabling boundary-scan testing, firmware flashing, and real-time debugging of all the team’s custom PCBs.",
      "Debugged hardware/firmware integration issues using J-Link and GDB to trace communication faults across CAN and UART interfaces."
    ],
    "tags": []
  },
  {
    "id": 2,
    "role": "Firmware Engineer Intern",
    "company": "Verdi",
    "companyUrl": "https://www.verdi.ag",
    "location": "Vancouver, BC",
    "period": "Jan 2026 - Present",
    "achievements": [
      "Worked on migrating and configuring firmware written in C to the Zephyr real-time operating system (RTOS) from FreeRTOS, including adapting board configuration, build system, and application code (CMake, Device Tree overlays).",
      "Implemented microvalve firmware control to ensure safe boot, restore persisted valve/fault state, and run watchdog-supervised real-time control for valve actuation, sensing, and communications across operating modes.",
      "Integrated and validated communication with the RAK1337 LoRa radio module, implementing initialization, data handling, and RTOS-safe asynchronous message processing.",
      "Developed firmware test utilities by implementing a CLI command to stress-test the onboard LittleFS storage, generating datastreams and writing data until filesystem capacity was reached.",
      "Used logic analyzers to debug hardware/firmware integration issues by capturing and analyzing digital communication signals and timing behavior across embedded interfaces."
    ],
    "tags": []
  }
];

export const resumeEducation: Education[] = [];

export const resumeSkills: string[] = [
  "C/C++",
  "Java",
  "Python",
  "SystemVerilog",
  "FreeRTOS/Zephyr RTOS",
  "Embedded Linux",
  "Device Drivers",
  "Interrupt Systems",
  "CAN Bus",
  "UART",
  "I2C",
  "DMA",
  "LoRa",
  "BLE",
  "STM32Cube IDE",
  "Visual Studio Code",
  "Git/GitHub",
  "GDB Altium",
  "Linux",
  "Segger J-Link",
  "CMake"
];

export default resumeExperiences;
