// AUTO-GENERATED by scripts/parse-resume.mjs
// Re-runs automatically on `npm run dev` and `npm run build`.
// Do not edit this file manually.
import type { Experience } from "./experiences";
import type { Education } from "./education";

const resumeExperiences: Experience[] = [
  {
    "id": 1,
    "role": "Firmware Engineer Intern",
    "company": "Verdi",
    "companyUrl": "https://www.verdi.ag",
    "location": "Vancouver, BC",
    "period": "Jan 2026 – Present",
    "achievements": [
      "Led migration of embedded C firmware from FreeRTOS to Zephyr RTOS, re-architecting task scheduling and driver interfaces, adapting CMake build systems and device tree overlays for scalable multi-board support.",
      "Implemented micro-valve control firmware using GPIO and RTOS threads, enabling automated valve actuation with safe boot, continuous state recovery, and watchdog-supervised real-time operation.",
      "Integrated and validated LoRa communication (RAK1337), implementing initialization, packet handling, and RTOS-safe asynchronous message processing.",
      "Designed and implemented a CI/CD pipeline for pull requests using GitHub Actions, triggering builds and unit tests based on board-specific file changes, and enforcing code quality with automated clang-format checks.",
      "Developed CLI firmware to stress-test LittleFS storage by generating high-volume data streams to test capacity.",
      "Used logic analyzers used to debug hardware/firmware issues by analyzing signal timing and communication behavior across embedded interfaces."
    ],
    "tags": []
  },
  {
    "id": 2,
    "role": "Embedded Systems / Firmware Engineer",
    "company": "UBC Solar Racing (Student Design Team)",
    "companyUrl": "https://ubcsolar.com",
    "location": "Vancouver, BC",
    "period": "Sep 2024 – Present",
    "achievements": [
      "Led firmware development for the Driver Dashboard subsystem, implementing vehicle drive-state control logic as a safety-critical state machine while integrating CAN bus messaging and hardware abstraction layers.",
      "Built a Raspberry Pi–based Python gateway connected to a Netgear hotspot to parse vehicle telemetry data and stream it to InfluxDB/Grafana, reducing latency ( < 2 seconds) and enabling real-time remote monitoring.",
      "Implemented GPS data acquisition firmware as a FreeRTOS thread that parsed NMEA sentences (GGA, GLL, GSA, RMC, VTG, GSV), validated checksums, and packaged results into CAN frames.",
      "Designed and implemented a FreeRTOS-based cruise control system, using a custom PI controller with real-time force modeling (drag, rolling resistance, hill climbing) for precise speed regulation, fusing IMU and CAN data with a Kalman filter, and ensuring critical safety logic conditions.",
      "Designed Segger J-Link interfaces for new-generation PCBs, enabling firmware flashing, boundary-scan testing, and real-time debugging."
    ],
    "tags": []
  }
];

export const resumeEducation: Education[] = [];

export const resumeSkills: string[] = [
  "C",
  "C++",
  "Java",
  "Python",
  "SystemVerilog",
  "Assembly",
  "FreeRTOS",
  "Zephyr RTOS",
  "Embedded Linux",
  "CMake",
  "Device Drivers",
  "Interrupt Systems",
  "CAN",
  "UART",
  "I2C",
  "DMA",
  "LoRa",
  "BLE",
  "STM32",
  "ESP32",
  "Logic Analyzer",
  "Oscilloscope",
  "J-Link",
  "GDB",
  "Makefile"
];

export default resumeExperiences;
